// VolEsti (volume computation and sampling library)

// Licensed under GNU LGPL.3, see LICENCE file

#ifndef RANDOM_WALKS_GREAT_CYCLE_WALK_HELPERS_HPP
#define RANDOM_WALKS_GREAT_CYCLE_WALK_HELPERS_HPP

#include <cmath>
#include <iostream>
#include <limits>

#include <Eigen/Eigen>

#include "sampling/sphere.hpp"

/// Rotate p along the great circle generated by the tangent direction v,
/// then remove floating-point radial drift.
///
/// On entry, Ar and Av cache A*p and A*v. After scaling they are propagation
/// operands; the next optimized recurrence produces A*normalized_p.
template <typename Point>
struct UpdateGreatCirclePoint
{
    typedef typename Point::FT NT;
    typedef typename Point::Coeff VT;

    inline static bool apply(Point& p,
                             Point const& v,
                             NT const& lambda,
                             VT& Ar,
                             VT& Av)
    {
        VT next =
            std::cos(lambda) * p.getCoefficients() +
            std::sin(lambda) * v.getCoefficients();

        NT const norm = next.norm();

        if (!std::isfinite(norm) ||
            norm <= std::numeric_limits<NT>::epsilon())
        {
            return false;
        }

        next /= norm;
        Ar /= norm;
        Av /= norm;

        p = Point(next);
        return true;
    }
};

/// Generates a random unit direction in the tangent plane of the unit sphere
/// at p.
///
/// A standard Gaussian vector z is projected onto the tangent plane:
///     v = z - p (p^T z),
/// and the result is normalized.
template <typename Point>
struct GetDirectionTangentPlane
{
    typedef typename Point::FT NT;
    typedef typename Point::Coeff VT;

    template <typename RandomNumberGenerator>
    inline static Point apply(Point const& p,
                              RandomNumberGenerator& rng)
    {
        VT z =
            GetDirection<Point>::apply(
                static_cast<unsigned int>(p.dimension()),
                rng,
                false)
                .getCoefficients();

        VT const& p_coeffs = p.getCoefficients();
        VT v = z - p_coeffs * p_coeffs.dot(z);

        NT norm = v.norm();

        while (norm == NT(0))
        {
            z =
                GetDirection<Point>::apply(
                    static_cast<unsigned int>(p.dimension()),
                    rng,
                    false)
                    .getCoefficients();

            v = z - p_coeffs * p_coeffs.dot(z);
            norm = v.norm();
        }

        v /= norm;

        return Point(v);
    }
};

#endif
