#ifndef RANDOM_WALKS_SIMPLEX_BALL_VOLUME_ESTIMATOR_HPP
#define RANDOM_WALKS_SIMPLEX_BALL_VOLUME_ESTIMATOR_HPP

#include <cstddef>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <vector>
#include <algorithm>

#include <Eigen/Eigen>

#include "random_walks/great_cycle_walk_helpers.hpp"
#include "random_walks/uniform_great_cycle_walk.hpp"

/// Result of estimating the relative spherical volume of a nested
/// simplex-ball body.
///
/// ratio approximates:
///     volume(inner_body) / volume(outer_body)
template <typename NT>
struct SimplexBallRatioEstimate
{
    NT ratio;
    std::size_t total_draws;
    std::size_t inside_draws;
    // Indicates that the inherited moving-window heuristic stabilized.
    // It is not a rigorous MCMC error bound.
    bool converged;
};

/// Estimate volume(inner_body) / volume(outer_body) using samples
/// generated by GCW on one connected component of outer_body.
///
/// The estimate is the fraction of sampled outer-body points that also
/// belong to inner_body. Convergence follows the moving-window logic of
/// the low_volatility GCWEstimator.
///
/// inner_body must be nested in the connected component of outer_body
/// reached from start. The function does not verify this subset relation.
template <
    typename OuterBody,
    typename InnerBody,
    typename RNGType>
SimplexBallRatioEstimate<typename OuterBody::NT>
estimate_simplex_ball_volume_ratio(
    OuterBody const& outer_body,
    InnerBody const& inner_body,
    typename OuterBody::PointType const& start,
    unsigned int walk_length,
    std::size_t window_length,
    typename OuterBody::NT relative_error,
    std::size_t max_draws,
    RNGType& rng,
    unsigned int burnin = 0)
{
    typedef typename OuterBody::NT NT;
    typedef typename OuterBody::PointType Point;
    typedef GCWalk::template Walk<OuterBody, RNGType> EstimatorWalk;

    if (outer_body.dimension() != inner_body.dimension())
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "body dimensions must agree");
    }

    // Great-circle updates are performed around the origin.
    // The caller must shift both bodies before invoking the estimator.
    NT const center_tolerance = NT(1e-10);
    NT const outer_center_norm =
        outer_body.get_center().norm();
    NT const inner_center_norm =
        inner_body.get_center().norm();

    if (!std::isfinite(outer_center_norm) ||
        !std::isfinite(inner_center_norm) ||
        outer_center_norm > center_tolerance ||
        inner_center_norm > center_tolerance)
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "bodies must be centered at the origin");
    }

    if (walk_length == 0)
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "walk length must be positive");
    }

    if (window_length < 2)
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "window length must be at least two");
    }

    if (!std::isfinite(relative_error) ||
        relative_error <= NT(0))
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "relative error must be positive and finite");
    }

    if (max_draws < window_length)
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "max draws must be at least the window length");
    }

    // A short sequence of identical cumulative ratios can make the moving
    // window appear stable immediately. Delay convergence until a separate
    // draw floor tied to the requested tolerance has also been reached.
    // This is still a heuristic for correlated MCMC samples, not an error
    // guarantee.
    NT const tolerance_draw_floor =
        std::ceil(
            NT(4) /
            (relative_error * relative_error));

    std::size_t accuracy_minimum_draws;

    if (!std::isfinite(tolerance_draw_floor) ||
        tolerance_draw_floor >=
            static_cast<NT>(
                std::numeric_limits<std::size_t>::max()))
    {
        accuracy_minimum_draws =
            std::numeric_limits<std::size_t>::max();
    }
    else
    {
        accuracy_minimum_draws =
            static_cast<std::size_t>(tolerance_draw_floor);
    }

    std::size_t const minimum_draws =
        std::max(window_length, accuracy_minimum_draws);

    Point p = start;

    NT const sphere_tolerance = NT(1e-8);
    NT const squared_radius =
        p.getCoefficients().squaredNorm();

    if (!std::isfinite(squared_radius) ||
        std::abs(squared_radius - NT(1)) > sphere_tolerance)
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "starting point must lie on the unit sphere");
    }

    if (outer_body.is_in(p, NT(1e-10)) == 0)
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_volume_ratio: "
            "starting point is outside the outer body");
    }

    EstimatorWalk walk(outer_body, p, rng);

    if (burnin > 0)
    {
        walk.apply(outer_body, p, burnin, rng);
    }

    std::vector<NT> recent_estimates(window_length, NT(0));

    std::size_t total_draws = 0;
    std::size_t inside_draws = 0;
    std::size_t window_position = 0;
    std::size_t window_filled = 0;

    NT ratio = NT(0);

    while (total_draws < max_draws)
    {
        walk.apply(outer_body, p, walk_length, rng);

        ++total_draws;

        if (inner_body.is_in(p, NT(1e-10)) == -1)
        {
            ++inside_draws;
        }

        ratio =
            static_cast<NT>(inside_draws) /
            static_cast<NT>(total_draws);

        recent_estimates[window_position] = ratio;

        window_position =
            (window_position + 1) % window_length;

        if (window_filled < window_length)
        {
            ++window_filled;
        }

        if (total_draws >= minimum_draws &&
            window_filled == window_length)
        {
            std::pair<
                typename std::vector<NT>::const_iterator,
                typename std::vector<NT>::const_iterator>
                bounds = std::minmax_element(
                    recent_estimates.begin(),
                    recent_estimates.end());

            NT const minimum = *bounds.first;
            NT const maximum = *bounds.second;

            // Do not report convergence before observing at least one
            // point in the inner body.
            if (maximum > NT(0) &&
                (maximum - minimum) / maximum <=
                    relative_error / NT(2))
            {
                return SimplexBallRatioEstimate<NT>{
                    ratio,
                    total_draws,
                    inside_draws,
                    true};
            }
        }
    }

    return SimplexBallRatioEstimate<NT>{
        ratio,
        total_draws,
        inside_draws,
        false};
}

/// Multiply the nested volume ratios along one root-to-component path.
///
/// If the common root has volume V0 and the path ratios are
/// V1/V0, V2/V1, ..., Vk/V(k-1), their product is Vk/V0.
/// The unknown common factor V0 cancels when component weights
/// are subsequently normalized.
template <typename NT>
NT combine_simplex_ball_volume_ratios(
    std::vector<SimplexBallRatioEstimate<NT>> const& estimates,
    bool require_convergence = true)
{
    NT component_weight = NT(1);

    for (SimplexBallRatioEstimate<NT> const& estimate : estimates)
    {
        if (!std::isfinite(estimate.ratio) ||
            estimate.ratio < NT(0) ||
            estimate.ratio > NT(1))
        {
            throw std::invalid_argument(
                "combine_simplex_ball_volume_ratios: "
                "ratios must be finite and lie in [0, 1]");
        }

        if (require_convergence && !estimate.converged)
        {
            throw std::runtime_error(
                "combine_simplex_ball_volume_ratios: "
                "a ratio estimate did not converge");
        }

        component_weight *= estimate.ratio;
    }

    return component_weight;
}

/// Convert one nested-ratio path per component into raw component weights.
///
/// The returned weights can be passed directly to
/// run_simplex_ball_multichain(), which normalizes them.
template <typename NT>
std::vector<NT> simplex_ball_component_weights_from_ratio_paths(
    std::vector<
        std::vector<SimplexBallRatioEstimate<NT>>> const&
        component_ratio_paths,
    bool require_convergence = true)
{
    if (component_ratio_paths.empty())
    {
        throw std::invalid_argument(
            "simplex_ball_component_weights_from_ratio_paths: "
            "no component paths");
    }

    std::vector<NT> component_weights;
    component_weights.reserve(component_ratio_paths.size());

    for (std::vector<SimplexBallRatioEstimate<NT>> const& path :
         component_ratio_paths)
    {
        component_weights.push_back(
            combine_simplex_ball_volume_ratios(
                path,
                require_convergence));
    }

    return component_weights;
}

/// Estimate one raw volume weight for each caller-supplied body path.
///
/// Each component_body_paths[i] must already identify one connected
/// component and be ordered from a common outer reference body to its
/// final component body. The function estimates every adjacent volume
/// ratio and multiplies the ratios along the path. It does not discover
/// components or construct these paths.
template <
    typename Body,
    typename RNGType>
std::vector<typename Body::NT>
estimate_simplex_ball_component_weights_from_body_paths(
    std::vector<std::vector<Body>> const& component_body_paths,
    std::vector<typename Body::PointType> const& starting_points,
    unsigned int walk_length,
    std::size_t window_length,
    typename Body::NT per_ratio_relative_error,
    std::size_t max_draws_per_ratio,
    RNGType& rng,
    unsigned int burnin = 0)
{
    typedef typename Body::NT NT;
    typedef typename Body::PointType Point;

    if (component_body_paths.empty())
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_component_weights_from_body_paths: "
            "no component body paths");
    }

    if (starting_points.size() != component_body_paths.size())
    {
        throw std::invalid_argument(
            "estimate_simplex_ball_component_weights_from_body_paths: "
            "number of starting points must equal number of paths");
    }

    std::vector<NT> component_weights;
    component_weights.reserve(component_body_paths.size());

    for (std::size_t component = 0;
         component < component_body_paths.size();
         ++component)
    {
        std::vector<Body> const& path =
            component_body_paths[component];

        if (path.empty())
        {
            throw std::invalid_argument(
                "estimate_simplex_ball_component_weights_from_body_paths: "
                "a component path is empty");
        }

        Point const& start = starting_points[component];

        // A final-component starting point must lie in every body of
        // a correctly nested root-to-component path.
        for (Body const& body : path)
        {
            if (body.is_in(start, NT(1e-10)) == 0)
            {
                throw std::invalid_argument(
                    "estimate_simplex_ball_component_weights_from_body_paths: "
                    "starting point is outside a body in its path");
            }
        }

        std::vector<SimplexBallRatioEstimate<NT>> path_estimates;
        path_estimates.reserve(
            path.size() > 0 ? path.size() - 1 : 0);

        for (std::size_t level = 0;
             level + 1 < path.size();
             ++level)
        {
            path_estimates.push_back(
                estimate_simplex_ball_volume_ratio(
                    path[level],
                    path[level + 1],
                    start,
                    walk_length,
                    window_length,
                    per_ratio_relative_error,
                    max_draws_per_ratio,
                    rng,
                    burnin));
        }

        component_weights.push_back(
            combine_simplex_ball_volume_ratios(
                path_estimates,
                true));
    }

    return component_weights;
}

#endif
